n = int(input('Digite algum valor e veja sua tabuada '))
print('{} x 1 é igual a: {} '.format(n, n * 1))
print('{} x 1 é igual a: {} '.format(n, n * 2))
print('{} x 1 é igual a: {} '.format(n, n * 3))
print('{} x 1 é igual a: {} '.format(n, n * 4))
print('{} x 1 é igual a: {} '.format(n, n * 5))
print('{} x 1 é igual a: {} '.format(n, n * 6))
print('{} x 1 é igual a: {} '.format(n, n * 7))
print('{} x 1 é igual a: {} '.format(n, n * 8))
print('{} x 1 é igual a: {} '.format(n, n * 9))
print('{} x 1 é igual a: {} '.format(n, n * 10))
